version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: ../infra/Dockerfile.frontend
    container_name: travel_planner_frontend
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: ../infra/Dockerfile.backend
    container_name: travel_planner_backend
    env_file:
      - .env
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    command: ["npm", "run", "start:dev"]
